c({"name": "g.errorCatcher.handleInitialException", "params": {"caughtException": {"description": "<p>The caught exception.</p>", "type": "Error", "optional": false, "order": 0, "name": "caughtException"}, "fileName": {"description": "<p>The name of the JS file where the exception occured.</p>", "type": "string", "optional": false, "order": 1, "name": "fileName"}}, "ret": {"type": "undefined", "description": ""}, "type": "function", "comment": "<p>Handles exceptions from the try { } catch { } block added around all of our compiled JS by our Closure Compiler\nconfiguration. This handles exceptions that occur during the intiial execution of the script.</p>", "src": "appDev/node_modules/socket.io/node_modules/socket.io-client/node_modules/uglify-js/tmp/app.js", "line": 13483, "children": []})